"""Docx 表格提取 + 元数据读取测试。"""
from __future__ import annotations

import zipfile
from pathlib import Path

from paperguard.detectors.g4_metadata_forensics import extract_docx_metadata
from paperguard.extractor.docx_tables import parse_docx_tables


def _make_minimal_docx(path: Path, with_table: bool = False) -> None:
    """造一个最小可用的 docx：含 core.xml / app.xml / document.xml。"""
    w_ns = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
    if with_table:
        body = f"""
        <w:tbl xmlns:w="{w_ns}">
          <w:tr><w:tc><w:p><w:r><w:t>Sample</w:t></w:r></w:p></w:tc>
                 <w:tc><w:p><w:r><w:t>Value</w:t></w:r></w:p></w:tc></w:tr>
          <w:tr><w:tc><w:p><w:r><w:t>A</w:t></w:r></w:p></w:tc>
                 <w:tc><w:p><w:r><w:t>1.50</w:t></w:r></w:p></w:tc></w:tr>
          <w:tr><w:tc><w:p><w:r><w:t>B</w:t></w:r></w:p></w:tc>
                 <w:tc><w:p><w:r><w:t>2.55</w:t></w:r></w:p></w:tc></w:tr>
        </w:tbl>
        """
    else:
        body = ""

    document_xml = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="{w_ns}">
  <w:body>{body}</w:body>
</w:document>"""

    core_xml = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties
    xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:dcterms="http://purl.org/dc/terms/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:creator>python-docx</dc:creator>
  <cp:lastModifiedBy></cp:lastModifiedBy>
  <dcterms:created xsi:type="dcterms:W3CDTF">2013-12-23T23:15:00Z</dcterms:created>
  <dcterms:modified xsi:type="dcterms:W3CDTF">2013-12-23T23:15:00Z</dcterms:modified>
  <dc:description>generated by python-docx</dc:description>
  <cp:revision>1</cp:revision>
</cp:coreProperties>"""

    app_xml = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">
  <Application>python-docx</Application>
  <TotalTime>0</TotalTime>
  <AppVersion>14.0000</AppVersion>
</Properties>"""

    rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
    Target="word/document.xml"/>
</Relationships>"""

    content_types = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="xml" ContentType="application/xml"/>
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Override PartName="/word/document.xml"
    ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/docProps/core.xml"
    ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml"
    ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>"""

    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", content_types)
        z.writestr("_rels/.rels", rels)
        z.writestr("docProps/core.xml", core_xml)
        z.writestr("docProps/app.xml", app_xml)
        z.writestr("word/document.xml", document_xml)


def test_docx_table_extraction(tmp_path: Path) -> None:
    p = tmp_path / "doc.docx"
    _make_minimal_docx(p, with_table=True)
    tables = parse_docx_tables(p)
    assert "table_1" in tables
    df = tables["table_1"]
    assert list(df.columns) == ["Sample", "Value"]
    assert len(df) == 2
    # Value 列应被数值化
    assert df["Value"].dtype.kind in {"f", "i"}


def test_docx_no_tables(tmp_path: Path) -> None:
    p = tmp_path / "empty.docx"
    _make_minimal_docx(p, with_table=False)
    assert parse_docx_tables(p) == {}


def test_docx_metadata_extraction(tmp_path: Path) -> None:
    p = tmp_path / "doc.docx"
    _make_minimal_docx(p)
    meta = extract_docx_metadata(p)
    assert meta["creator"] == "python-docx"
    assert meta["revision"] == 1
    assert meta["application"] == "python-docx"
    assert meta["total_edit_minutes"] == 0


